// Code generated by "stringer -type=opCode"; DO NOT EDIT

package main

import "fmt"

const _opCode_name = "PRINPUSHPOPRETSTOLOADBIN_OPPUSH_IPPUSH_FPJMPCJMPHALT"

var _opCode_index = [...]uint8{0, 4, 8, 11, 14, 17, 21, 27, 34, 41, 44, 48, 52}

func (i opCode) String() string {
	if i < 0 || i >= opCode(len(_opCode_index)-1) {
		return fmt.Sprintf("opCode(%d)", i)
	}
	return _opCode_name[_opCode_index[i]:_opCode_index[i+1]]
}
